### ISSUE TITLE
No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by mitya12342** [ak9250/gpt-2-colab#13]
I am new to tensorflow but something seems changed. I get this when i try to train
```
Traceback (most recent call last):
  File "./train.py", line 14, in <module>
    import model, sample, encoder
  File "/content/gpt-2/src/model.py", line 3, in <module>
    from tensorflow.contrib.training import HParams
ModuleNotFoundError: No module named 'tensorflow.contrib'
```
I even tried `%tensorflow_version 1.x`

**Comment by ddaskan** [comment]
You need specific version such as 1.12 which you cannot do via `%tensorflow_version 1.x`. Fortunately, there is a workaround to downgrade, try to apply as the link; https://stackoverflow.com/a/54445624/6401202

**Comment by Kreijstal** [comment]
Can you provide an example google colab link?
